# Generated by Django 6.0.4 on 2026-05-06 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_categpry_product_image_product_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categpry',
            new_name='category',
        ),
    ]
